### ISSUE TITLE
직원소개

### ISSUE THREAD

**Issue by yubmun** [yubmun/jquery#2]
## 2022-01-11 오늘의 CSS 공부
* Part2 실전 퍼블리싱 제작
  * 순서 체크 가상클래스 활용한 실전 예제 제작 (개인프로필 카드 UI 호버 이펙트)
<hr/>

### 직원소개.html
```html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
  <link rel="stylesheet" href="css/2.직원소개.css">
</head>
<body>
  <div class="container">
    <div class="card">
      <img src="/img/crew-01.jpg">
      <div class="content">
        <h2>Handsome Guy <span>Developer</span></h2>
        <p>
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Qui architecto cumque fuga et voluptatum sed totam nemo ex recusandae? Perspiciatis!
        </p>
        <div class="sns">
          <a href="#none"><i class="fa fa-facebook"></i></a>
          <a href="#none"><i class="fa fa-twitter"></i></a>
          <a href="#none"><i class="fa fa-instagram"></i></a>
        </div>
      </div>
    </div>
    <div class="card">
      <img src="/img/crew-02.jpg">
      <div class="content">
        <h2>Handsome Guy <span>Developer</span></h2>
        <p>
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Qui architecto cumque fuga et voluptatum sed totam nemo ex recusandae? Perspiciatis!
        </p>
        <div class="sns">
          <a href="#none"><i class="fa fa-facebook"></i></a>
          <a href="#none"><i class="fa fa-twitter"></i></a>
          <a href="#none"><i class="fa fa-instagram"></i></a>
        </div>
      </div>
    </div>
    <div class="card">
      <img src="/img/crew-03.jpg">
      <div class="content">
        <h2>Handsome Guy <span>Developer</span></h2>
        <p>
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Qui architecto cumque fuga et voluptatum sed totam nemo ex recusandae? Perspiciatis!
        </p>
        <div class="sns">
          <a href="#none"><i class="fa fa-facebook"></i></a>
          <a href="#none"><i class="fa fa-twitter"></i></a>
          <a href="#none"><i class="fa fa-instagram"></i></a>
        </div>
      </div>
    </div>
  </div>
</body>
</html>
```
html 코드가 매우 복잡해 보인다.
먼저 .container > .card > img, .content > h2(>span), p, .sns > a > i 로 구성되어있다.
하나의 직원 카드마다 img와 마우스가 hover 되었을 때 필요한 .content 가 큰 틀이며
.content에는 이름을 작성하는 h2, 글자크기를 다르게 하기위한 자식요소로 span , p 태그가 있으며 설명 밑에 sns 로고가 표기되므로
a태그와 i 태그를 삽입하여 fontawesome 의 sns 코드들을 입력해주었다.

<hr/>

### 직원카드.css
```css
@import url('https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css');

.container{
  display:flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
}
.card{
  margin:10px;
  position:relative;
  width: 300px;
  height: 400px;
  overflow:hidden;
  transition:0.5s;
}
.content{
  position:absolute;
  width: inherit;
  height: inherit;
  top:100%;
  left:0;
  padding: 20px;
  padding-top:130px;
  box-sizing: border-box;
  background:linear-gradient(to top, crimson, transparent);
  color:white;
  text-align: center;
  transition:0.5s;
}
.card:nth-child(1) .content{
  background:linear-gradient(to top, crimson, transparent);
}
.card:nth-child(2) .content{
  background:linear-gradient(to top, dodgerblue, transparent);
}
.card:nth-child(3) .content{
  background:linear-gradient(to top, yellowgreen, transparent);
}
.content h2{
  font-size: 30px;
}
.content h2 span{
  display:block;
  font-size: 14px;
  color:gold;
  margin-top:10px;
}
.sns a{
  color:white;
  border: 1px solid white;
  border-radius: 50%;
  display:inline-block;
  width: 20px;
  height: 20px;
  font-size: 14px;
  text-align: center;
  line-height: 20px;
}
.card:hover .content{
  top:0;
}
.card:hover {
  transform:translateY(-20px);
  box-shadow:0 10px 20px black;
}
```
이번 실습에서 가장 중요한 css 코드는, :nth-child 가상클래스이다.

```css
.card:nth-child(1) .content{
  background:linear-gradient(to top, crimson, transparent);
}
.card:nth-child(2) .content{
  background:linear-gradient(to top, dodgerblue, transparent);
}
.card:nth-child(3) .content{
  background:linear-gradient(to top, yellowgreen, transparent);
}
```
이 부분은 각 이미지와 동일한 위치에 있는 content div들을 지정해줄 때에 유의해야 할 점이다.
.card div 들은 총 3개로 자식요소로 content를 모두 갖고 있다. 위와같이 코딩하지 않고
.content:nth-child(1) {} 로 작성한다면, 올바르게 선택되지 않으므로, 위와 같이 코드를 작성해야 한다.
위 코드는 .card div 첫번째 중, .content의 {속성값} 로 해석하면 됨.
background : linear-gradient 는 (to top / 탑으로 방향, crimson / 크림슨 색에서 , transparent / 투명색으로)
즉, 아래에선 크림슨 위로갈수록 투명해진다는 속성값이다.

<hr/>
![image](https://user-images.githubusercontent.com/89332480/148922195-b4fd7ee3-7f6f-4033-b88f-bbd8a36028e4.png)
