### ISSUE TITLE
검색창 만들기

### ISSUE THREAD

**Issue by yubmun** [yubmun/jquery#3]
## 2022-01-11 오늘의 CSS 공부
* Part2 실전 퍼블리싱 제작
  * 폼 관련 가상클래스를 활용한 실전 퍼블리싱 (배경 이미지 풀 스크린 검색창)

###검색창.html
```html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
  <link rel="stylesheet" href="css/2.검색창.css">
</head>
<body>
  <form class="search">
    <h1>What are you looking for?</h1>
    <input type="text" placeholder="Type...">
    <input type="submit" value="Search">
  </form>
</body>
</html>
```
너무나 간단한 html 코드다. 여기서 중요하게 볼 점은
placeholder 로 input type=text 태그 배경에 써 놓을 글씨를 지정하는 코드이다.
마찬가지로 input type=submit 에는 value 값으로 지정한다.

![image](https://user-images.githubusercontent.com/89332480/148923672-3d8007a4-8b72-4ad5-9dc4-ebf412285e26.png)

<hr/>

### 검색창.css
```css
body{
  background:url(/img/snow-photo.jpg) no-repeat center center fixed;
}
body:before{
  content:'';
  position:absolute;
  background-color: rgba(0, 0, 0, 0.657);
  height: 100%;
  width: 100%;
  top:0;
  left:0;
  z-index:-1;
  /* z-index 값을 -1로 줘서, form 요소보다 뒤에 위치할 수 있도록 설정 */
}
.search{
  /* border: 1px solid white; */
  position:absolute;
  top:50%;
  left:50%;
  transform:translate(-50%, -50%);
}
.search h1{
  text-align: center;
  font-weight: normal;
  color:white;
}
.search input[type=text]{
  width: 300px;
  padding:15px;
  border: none;
  margin-right: -6px;
  border-radius: 40px 0 0 40px;
  outline:none;
  padding-left:30px;
  box-sizing: border-box;
}
.search input[type=submit]{
  width: 90px;
  padding:15px;
  border:none;
  border-radius: 0 40px 40px 0;
  cursor:pointer;
  background-color: orange;
  color:white;
  outline:none;
  box-sizing: border-box;
}
.search input[type=text]::placeholder{
  font-size: 20px;
  font-style: italic;
}
/* CSS3 부터 생긴 가상클래스는 :: 콜론을 두개 써줘야 함. */
/* input[type=text] [] 대괄호로 묶여있는 것을 속성선택자라고 함 */

.search input[type=submit]:hover{
  background-color: rgb(77, 65, 3);
}
```
css 파일에서 중요하게 볼 코드는
```css
body:before{
  content:'';
  position:absolute;
  background-color: rgba(0, 0, 0, 0.657);
  height: 100%;
  width: 100%;
  top:0;
  left:0;
  z-index:-1;
}
```
z-index의 값이다. body태그의 배경을 url로 이미지 파일을 지정해줬기 때문에, body:before 가상클래스 태그에 배경색을 설정했을때
작성한 form 태그의 요소들보다 앞에 위치하기때문에 해당 태그들 위에 덮여있게 된다. 때문에 z-index 값을 -1로 지정하여 요소들 뒤에 위치할 수 있게 한다.

```css
.search input[type=text]::placeholder{
  font-size: 20px;
  font-style: italic;
}
```
위 코드중 :: 콜론이 두개 찍혀있는 이유는 CSS3 부터 생긴 가상클래스이기 때문이다.

![image](https://user-images.githubusercontent.com/89332480/148924552-31a8c071-97ec-4d89-b239-1cada137f8a1.png)
