### ISSUE TITLE
로그인 화면

### ISSUE THREAD

**Issue by yubmun** [yubmun/jquery#4]
## 2022-01-11 오늘의 CSS 공부
* Part2 실전 퍼블리싱 제작
  * 폼 관련 가상클래스를 활용한 실전 퍼블리싱 (로그인 화면)
<hr/>

### 로그인화면.html
```html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
  <link rel="stylesheet" href="css/2.로그인화면.css">
</head>
<body>
  <form class="login">
    <span>Email</span>
    <input type="email" placeholder="Email Address">
    <span>Password</span>
    <input type="password" placeholder="Password">
    <p>
      <label for="">
        <input type="checkbox">로그인 유지
      </label>
      <a href="#none" class="btn-forgot">비밀번호 잊음?</a>
    </p>
    <button>Log in</button>
  </form>
</body>
</html>
```
검색창과 동일하게 로그인 화면도 html 은 매우 단순하다.

### 로그인화면.css
```css
body{
  display:flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
}
a{
  color:#222;
  text-decoration: none;
}
.login {
  width: 800px;
  background-color: #f5f5f5;
  border: 1px solid #eee;
  border-radius: 5px;
  padding: 25px;
  box-sizing: border-box;
  box-shadow: 0 0 25px rgba(0, 0, 0, 0.39);
}
.login span{
  font-weight: bold;
  display: block;
  margin-top: 20px;
}
.login input[type=email], .login input[type=password]{
  width: 100%;
  padding: 15px;
  box-sizing: border-box;
  border: 1px solid #ddd;
  border-radius: 5px;
  transition:0.3s;
  padding-left:50px;
}
.login p{
  overflow: hidden;
  /* overflow:hidden 으로 자식요소에 float left right로 인해 높이값이 상실 된 것을 찾아준다. */
}
.login p label{
  float:left;
  cursor: pointer;
}
.login p .btn-forgot{
  float:right;
}
.login p .btn-forgot:hover{
  text-decoration: underline;
}
.login button{
  background-color: dodgerblue;
  color:white;
  width: 300px;
  padding: 10px;
  border-radius: 5px;
  border:none;
  cursor: pointer;
  font-size: 24px;
  transition:0.3s;
}
.login button:hover{
  background-color: rgb(8, 37, 66);
}
.login input[type=email]:hover, .login input[type=password]:hover{
  border: 1px solid dodgerblue;
  box-shadow: 0 0 5px dodgerblue;
}
.login input[type=email] {
  background:#fff url(/img/icon-email.png) no-repeat center left 10px;
}
.login input[type=password]{
  background: #fff url(/img/icon-lock.png) no-repeat center left 10px;
}
.login input[type=email]:focus::placeholder,
.login input[type=password]:focus::placeholder{
  visibility: hidden;
  opacity:0;
}
.login input[type=email]::placeholder,
.login input[type=password]::placeholder{
  opacity:1;
  transition:0.3s;
}
```
css 코드에서 주의할 점은

```css
.login p{
  overflow: hidden;
}
.login p label{
  float:left;
  cursor: pointer;
}
.login p .btn-forgot{
  float:right;
}
```
.login p 의 자식요소 label 과 .btn-forgot 에 float:left; 를 입력해줬기 때문에 부모요소인 .login p 는 높이 값을 상실하게 된다.
때문에, overflow:hidden; 속성을 부여해줘서 상실된 높이 값을 찾을 수 있게 설정해준다.

```css
.login input[type=email]:focus::placeholder,
.login input[type=password]:focus::placeholder{
  visibility: hidden;
  opacity:0;
}
```
.login 의 input type이 email인 input이 focus, 눌러졌을때, placeholder 배경으로 작성된 글을 감추고, 투명을 0으로 설정
visibility는 opacity 값을 주기 위해서 visible (보이게) hidden(안보이게) 설정하는 값이다.

![image](https://user-images.githubusercontent.com/89332480/148933443-14f2a569-aef0-418e-a652-c1ee846f569e.png)
