### ISSUE TITLE
jQuery 이용한 탭메뉴만들기

### ISSUE THREAD

**Issue by yubmun** [yubmun/jquery#5]
## 2022-01-11 오늘의 CSS 공부
* Part3 실전 퍼블리싱 제작 with jQuery
  * 탭 메뉴 콘텐츠 with jQuery

<hr/>

![image](https://user-images.githubusercontent.com/89332480/148934139-8047dee0-04ab-4586-8ee7-8776031cd0b5.png)

img를 클릭했을 때, filter:grayscale 의 값 변화, border-radius 의 변화, img 태그와 묶인 content의 변화를 jQuery를 활용하여
간단한 코드를 구성해보았다.

###탭메뉴.html

```html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <link rel="stylesheet" href="css/J.탭메뉴.css">
</head>
<body>
  <div class="testimonial-section">
    <h1><span>CodingWorks</span> Publishing Online Class with Inflearn</h1>
    <div class="testimonial-pic">
      <img class="active" src="/img/crew-01.jpg" data-alt="tab1">
      <img src="/img/crew-02.jpg" data-alt="tab2">
      <img src="/img/crew-03.jpg" data-alt="tab3">
      <img src="/img/face-01.jpg" data-alt="tab4">
    </div>
    <div class="testimonial">
      <div class="content active" id="tab1">
        <p>
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Perspiciatis reiciendis adipisci, quidem obcaecati nulla voluptates asperiores debitis alias odit minus quibusdam eaque libero fugiat quasi magni molestias veniam. Aliquid dolore sed iusto illo nulla ducimus quasi consequatur, non culpa unde molestiae harum accusamus at dolores repellat dolor id, possimus exercitationem velit ipsum, obcaecati voluptate incidunt ipsam? Nam repellat pariatur inventore velit perspiciatis, tempore labore, saepe quod repellendus laborum dolores! Natus soluta alias, sint et blanditiis eaque accusamus perferendis numquam repellendus.
        </p>
        <p>샐리 웹디자이너</p>
      </div>
      <div class="content" id="tab2">
          <p>
            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsa consectetur aliquid voluptas voluptatem rem optio corporis, aperiam aspernatur ipsum. Eos sequi vero eaque quo dolores in atque eligendi porro dolore, eius exercitationem! Facilis reiciendis dolorum autem, itaque esse atque doloremque non possimus, soluta labore, unde placeat earum velit libero. Ipsam aperiam tempora, illum assumenda vitae iure reiciendis commodi vel blanditiis culpa impedit quas velit dolore ipsum pariatur id repellat voluptatem itaque facere nobis. Quos itaque nostrum vero sapiente expedita? Corrupti.
          </p>
          <p>에이미 그래픽디자이너</p>
      </div>
      <div class="content" id="tab3">
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores ex illum quidem fugiat molestiae maiores quod reprehenderit. Nisi nobis ratione minima animi perspiciatis laudantium amet. Deserunt delectus, aut reprehenderit quis consequuntur ad culpa sed quo! Nisi, assumenda omnis? Fuga eligendi nihil dolore enim natus facere voluptas, provident est saepe vel iure libero incidunt corporis officiis illum at. Aperiam porro quaerat in eligendi optio aliquam cumque, unde vero asperiores quibusdam a impedit illo laboriosam ducimus at consectetur harum ipsa? Ut, nam!
        </p>
        <p>정호 개발자</p>
      </div>
      <div class="content" id="tab4">
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptas ratione quod excepturi est harum molestias incidunt architecto id sapiente omnis ad fugit quibusdam enim hic ipsam accusamus ut, beatae exercitationem nihil, perspiciatis autem suscipit? Optio obcaecati repudiandae earum assumenda itaque quod ab eum odit hic aut, distinctio et voluptates dignissimos ipsa, necessitatibus quidem quia saepe aperiam ut? Aut quae explicabo sequi consequatur iusto assumenda mollitia eaque iste, doloribus nesciunt nostrum ratione nam corporis necessitatibus cumque nulla eos. Sunt, cupiditate eveniet.
        </p>
        <p>크리스 프린팅디자이너</p>
      </div>
    </div>
  </div>

  <script>
    $('.testimonial-pic img').click(function(){
      $(this).addClass('active')
      $(this).siblings().removeClass('active')
      // 특정하지 않은것은 this
      $('.testimonial .content').removeClass('active')
      $('#' + $(this).attr('data-alt')).addClass('active')
      // tab1 을 변화시켜야함. $(this).attr('data-alt') == tab1
    })
  </script>
</body>
</html>
```
html구조는 복잡하지만, script 태그를 body 끝나는 지점 바로 위에 작성했다는 점만 기억하자.

```html
    <div class="testimonial-pic">
      <img class="active" src="/img/crew-01.jpg" data-alt="tab1">
      <img src="/img/crew-02.jpg" data-alt="tab2">
      <img src="/img/crew-03.jpg" data-alt="tab3">
      <img src="/img/face-01.jpg" data-alt="tab4">
...
      <div class="content active" id="tab1">
      <div class="content" id="tab2">
      <div class="content" id="tab3">
      <div class="content" id="tab4">
```
중요한 코드는 위의 코드이다. 첫번째 로딩되는 img 태그는 active 라는 클래스를 붙여주었다.
각 이미지마다 data-alt 라는 사용자 정의 속성을 작성하였고, tab1, tab2, tab3, tab4로 지정했다.
마찬가지로 해당 이미지와 함께 보여져야하는 4개의 .content에도 id 를 이미지와 맞게 부여하였다. (첫번째 content는 클래스명에 active가 추가되어있다.)

이렇게 지정해야, tab1 로 지정한 이미지를 눌렀을 때, content도 tab1로 지정된 컨텐츠가 나오게 된다.

<hr/>

### 탭메뉴.css
```css
body{
  background-color: #eee;
  display:flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
}
.testimonial-section{
  width: 800px;
  text-align: center;
  background-color: white;
  padding: 20px;
  border-radius: 10px;
  box-shadow: 0 0 10px black;
}
.testimonial-section h1{
  font-size: 25px;
  margin-bottom: 30px;
}
.testimonial-section h1 span{
  color:red;
}
.testimonial-pic img{
  width: 100px;
  height: 110px;
  filter:grayscale(1);
  margin: 5px;
  transition:0.3s;
  cursor: pointer;
}
.testimonial-pic img.active{
  border-radius: 50%;
  filter:grayscale(0);
  /* filter:none; 도 가능 */
}
.testimonial .content{
  display:none;
}
.testimonial .content.active{
  display: block;
}
.testimonial .content p:nth-child(2){
  font-weight: bold;
}
```
여기서 중요한 점은, .active로 지정된 클래스들의 속성값을 css 코드로 부여해줬다는 점이다.
즉, jQuery에서 활용할 속성값들이 미리 css에서 지정이 되어있기 때문에 선택자로 지정만 해준다면, 2,3,4 tab도 동일한 속성값을 가질 수 있다는 것이다.

<hr/>

### 스크립트를 보자
```js
  <script>
    $('.testimonial-pic img').click(function(){
      $(this).addClass('active')
      $(this).siblings().removeClass('active')
      // 특정하지 않은것은 this
      $('.testimonial .content').removeClass('active')
      $('#' + $(this).attr('data-alt')).addClass('active')
      // tab1 을 변화시켜야함. $(this).attr('data-alt') == tab1
    })
  </script>
```
위 html 코드에도 있지만, 자세히 알아보자.
해당 코드에는 addClass() , .siblings(), .removeClass(), attr()의 메서드가 사용되었다.
먼저, 
```css
$('.testimonial-pic img').click(function(){
})
```
 는, testimonial-pic 클래스에 있는 img가 클릭되었을때, 기능하라. 라는 의미이다.
그 기능들로
```css
$(this).addClass('active')
```
this는 사용자가 클릭한 img 를 나타내며, addClass로 css 코드로 부여된 active 속성값들을 만들어주는 것이다.
```css
$(this).siblings().removeClass('active')
```
동시에, 사용자가 클릭한 img의 형제요소들은, active 속성값들을 remove 해준다.
```css
$('.testimonial .content').removeClass('active')
```
이미지 변화와 동시에 content의 내용도 active속성이 빠진다.
```
$('#' + $(this).attr('data-alt')).addClass('active')
```
각 content마다 부여된 id 를 호출해주기 위해 '#' + 를 추가해준것이며
$(this).attr('data-alt') 는 사용자가 클릭한 img의 attr 속성, data-alt로 tab1, tab2, tab3, tab4 지정해준 사용자 지정값을 의미한다.
즉, tab1 은 첫번째 content, tab2 는 두번째 ~~
그 선택자들에게, addClass를 해줌으로써, content의 내용도 img가 눌렸을 때 동시에 작동할 수 있도록 짜여진 함수이다.
